### ISSUE TITLE
Packages build.log has moved breaking `install_dependencies.jl`

### ISSUE THREAD

**Issue by KristofferC** [tkf/IPython.jl#25]
In order to reduce the writes to the package directory, the build.log file was moved to scratch space:

https://github.com/JuliaLang/Pkg.jl/blob/aa8b07246c66d0c694777a88100c1ec1b38d121e/src/Operations.jl#L908-L925

 This means that the code: 

https://github.com/tkf/IPython.jl/blob/c00efd5938531c16c2fd06c2defeda61410243d9/test/install_dependencies.jl#L27-L30

doesn't work anymore since it is trying to read a non-existing file and errors.

**Comment by vtjnash** [comment]
bump
