### ISSUE TITLE
Cryptic error when the package is loaded, but julia isn't installed in Python

### ISSUE THREAD

**Issue by diegozea** [tkf/IPython.jl#4]
Hi!

When you do `using IPython` and `julia` isn't installed a cryptic error appears.
I see two ways to solve this and I don't know what do you prefer:

1. Install `julia` in Python using a build script and the Conda package, something similar to: https://github.com/JuliaDiffEq/FEniCS.jl/blob/master/deps/build.jl
2. Just try to `import julia` in Python and raise an informative error asking for julia installation.

It is a nice package, I hope this helps :)

Best regards,

**Comment by tkf** [comment]
Thanks :) Yea, error message should be clear.
